/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "Rcc.h"
#include "gpio.h"
#include "F4_delay.h"
#include "exti.h"

//uint8_t count = 0;
volatile uint8_t flag = 0;

void EXTI0_IRQHandler(void) {
    // Your code to handle the external interrupt (PA0 falling edge)

    // Clear the pending interrupt flag
    if (EXTI->PR & (1U << 0)) {
	 	flag = 1;

        EXTI->PR = (1U << 0);  // Clear the interrupt flag for EXTI0 (PA0)
    }
}
int main(void){

SysClockConfig();
GPIO_Config();
TIM9_Config();
exti_config();

//uint32_t check = 0;

while(1)
{
	if (flag)
	{
	 	GPIOC -> BSRR &= ~(1 << 13);
	 	GPIOC -> BSRR |= (1 << 29);
		Delay_ms(1000);
		flag = 0;
	}
	else {
		GPIOC -> BSRR |= (1 << 13);
	}

}
}
